CREATE TABLE IF NOT EXISTS questions (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_type TEXT NOT NULL CHECK (interview_type IN ('科研面','英语面','专业面','行为面')),
    question_text TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT '中等',
    major_scope TEXT NOT NULL DEFAULT '通用',
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interview_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id TEXT NOT NULL DEFAULT 'legacy',
    practice_mode TEXT NOT NULL CHECK (practice_mode IN ('全流程面试','单项面试')),
    interview_type TEXT CHECK (interview_type IN ('科研面','英语面','专业面','行为面')),
    user_major TEXT NOT NULL,
    research_count INTEGER NOT NULL DEFAULT 0,
    english_count INTEGER NOT NULL DEFAULT 0,
    professional_count INTEGER NOT NULL DEFAULT 0,
    behavior_count INTEGER NOT NULL DEFAULT 0,
    extra_requirement TEXT,
    status TEXT NOT NULL DEFAULT 'configured',
    started_at TEXT,
    finished_at TEXT,
    duration_seconds INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS materials (
    material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    visitor_id TEXT NOT NULL DEFAULT 'legacy',
    material_type TEXT NOT NULL CHECK (material_type IN ('简历','专业资料','院校面试真题','其他资料')),
    file_name TEXT NOT NULL,
    file_type TEXT,
    file_size INTEGER NOT NULL DEFAULT 0,
    content_text TEXT,
    parse_status TEXT NOT NULL DEFAULT 'success',
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES interview_sessions(session_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS session_questions (
    session_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    sequence_no INTEGER NOT NULL,
    interview_type TEXT NOT NULL CHECK (interview_type IN ('科研面','英语面','专业面','行为面')),
    question_text TEXT NOT NULL,
    source_scope TEXT NOT NULL CHECK (source_scope IN ('system','user_material')),
    source_type TEXT NOT NULL CHECK (source_type IN ('院校面试真题','专业资料','简历','系统题库')),
    source_question_id BIGINT,
    source_material_id BIGINT,
    parent_session_question_id BIGINT,
    generation_method TEXT NOT NULL DEFAULT 'rule',
    is_followup INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (session_id, sequence_no),
    FOREIGN KEY (session_id) REFERENCES interview_sessions(session_id) ON DELETE CASCADE,
    FOREIGN KEY (source_question_id) REFERENCES questions(question_id) ON DELETE SET NULL,
    FOREIGN KEY (source_material_id) REFERENCES materials(material_id) ON DELETE SET NULL,
    FOREIGN KEY (parent_session_question_id) REFERENCES session_questions(session_question_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS answers (
    answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_question_id BIGINT NOT NULL UNIQUE,
    session_id BIGINT NOT NULL,
    answer_text TEXT NOT NULL,
    answer_duration INTEGER NOT NULL DEFAULT 0,
    overall_score NUMERIC(5,1) NOT NULL,
    logic_score NUMERIC(5,1) NOT NULL,
    completeness_score NUMERIC(5,1) NOT NULL,
    accuracy_score NUMERIC(5,1) NOT NULL,
    clarity_score NUMERIC(5,1) NOT NULL,
    response_score NUMERIC(5,1) NOT NULL,
    weak_dimension TEXT NOT NULL,
    diagnosis TEXT NOT NULL,
    suggestion TEXT NOT NULL,
    reference_structure TEXT NOT NULL,
    evaluation_method TEXT NOT NULL DEFAULT 'rule',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_question_id) REFERENCES session_questions(session_question_id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES interview_sessions(session_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS session_feedback (
    feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL UNIQUE,
    helpful_score INTEGER NOT NULL CHECK (helpful_score BETWEEN 1 AND 5),
    relevance_score INTEGER NOT NULL CHECK (relevance_score BETWEEN 1 AND 5),
    comment TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES interview_sessions(session_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS event_logs (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    visitor_id TEXT NOT NULL DEFAULT 'legacy',
    event_name TEXT NOT NULL,
    page_name TEXT,
    event_params TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES interview_sessions(session_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_questions_type ON questions(interview_type, is_active);
CREATE INDEX IF NOT EXISTS idx_sessions_created ON interview_sessions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_visitor_created ON interview_sessions(visitor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_questions_session ON session_questions(session_id, sequence_no);
CREATE INDEX IF NOT EXISTS idx_answers_session ON answers(session_id);
CREATE INDEX IF NOT EXISTS idx_feedback_created ON session_feedback(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_materials_type ON materials(material_type, session_id);
CREATE INDEX IF NOT EXISTS idx_materials_visitor ON materials(visitor_id, uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_name_time ON event_logs(event_name, created_at);
CREATE INDEX IF NOT EXISTS idx_events_visitor_time ON event_logs(visitor_id, created_at DESC);

ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_logs ENABLE ROW LEVEL SECURITY;
